name: 'dbt_core_demo_cafe'  # プロジェクト名
version: '1.0.0'  # プロジェクトのバージョン
config-version: 2  # dbtの設定バージョン
profile: 'dbt_core_demo_cafe'  # 使用するプロファイル名

# 各種パスの設定（相対パス）
model-paths: ["models"]        # モデル（SQL変換ロジック）のフォルダ
analysis-paths: ["analyses"]   # 分析用SQLスクリプトのフォルダ
macro-paths: ["macros"]        # マクロ（再利用可能なコード）のフォルダ
seed-paths: ["seeds"]          # シードデータ（初期投入用CSV）のフォルダ
test-paths: ["tests"]          # テスト用SQLのフォルダ

target-path: "target"  # コンパイル後のSQLファイルが出力されるフォルダ

clean-targets:         # `dbt clean` 実行時に削除されるフォルダ
  - "target"
  - "dbt_packages"

# モデルごとの設定
# 詳細は公式ドキュメント: https://docs.getdbt.com/ja/docs/configuring-models

models:
  dbt_core_demo_cafe:
    +materialized: view  # デフォルトはビューとして作成

    staging:             # ステージング（生データの整形領域）
      +materialized: view

    intermediate:        # 中間処理用モデル
      +materialized: view

    marts:               # マート層（最終成果物、分析用データ）
      +materialized: table

# DuckDB用のプロファイル情報
# 外部の profiles.yml を使わずに接続設定できる
# 詳細: https://docs.getdbt.com/docs/core/connection-profiles#advanced-profile-configs

vars:
  dbt_project_name: dbt_core_demo_cafe  # 変数定義（例としてプロジェクト名）
