
name: 'dbt_core_demo_cafe'
version: '1.0.0'
config-version: 2
profile: 'dbt_core_demo_cafe'

model-paths: ["models"]
analysis-paths: ["analyses"]
macro-paths: ["macros"]
seed-paths: ["seeds"]
test-paths: ["tests"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to clean out on `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in a model's config block.

models:
  dbt_core_demo_cafe:
    +materialized: view

    staging:
      +materialized: view

    intermediate:
      +materialized: view

    marts:
      +materialized: table


# DuckDB specific profile configuration
# This allows the project to run without an external profiles.yml file
# For more details, see: https://docs.getdbt.com/docs/core/connection-profiles#advanced-profile-configs

vars:
  dbt_project_name: dbt_core_demo_cafe

